# Generated by Django 4.2.4 on 2023-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bio_profile_pic_alter_bio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
