# Generated by Django 4.2.4 on 2023-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bio_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Blank-Profile-Picture.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
