# Generated by Django 4.2.4 on 2023-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bio_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_by', models.CharField(max_length=100, null=True)),
                ('recommended_user', models.CharField(max_length=100, null=True)),
                ('Recommendation', models.TextField(max_length=5000, null=True)),
            ],
        ),
    ]
