# Generated by Django 4.2.4 on 2023-09-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_recommendations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='Recommendation',
            new_name='recommendation',
        ),
    ]
