# Generated by Django 4.2.4 on 2023-09-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_recommendation_recommendations_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='recommended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
