# Generated by Django 4.2.4 on 2023-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_recommendations_rec_created_at_alter_bio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='rec_created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
